batch_size: 4
iters: 100000

train_dataset:
  type: BJSCLC
  dataset_root: F:/DATASET/Beijing-small_cell_lung_cancer-pathology/patch_1024
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: train

val_dataset:
  type: BJSCLC
  dataset_root: F:/DATASET/Beijing-small_cell_lung_cancer-pathology/patch_1024
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: val

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

optimizer:
  type: sgd
  weight_decay: 0.0005

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0

loss:
  types:
    - type: CE_DSC_Loss
  coef: [1, 1]