batch_size: 4
iters: 100000

train_dataset:
  type: BJSCLC
  dataset_root: F:/DATASET/Beijing-small_cell_lung_cancer-pathology/patch_1024
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: train

val_dataset:
  type: BJSCLC
  dataset_root: F:/DATASET/Beijing-small_cell_lung_cancer-pathology/patch_1024
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: val

model:
  type: HS_UNet
  num_classes: 2
  use_deconv: True
  split: 5

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.00004

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0001

loss:
  types:
    - type: DiceLoss
  coef: [1]
